(define (problem prueba1-ej1)
    (:domain ejercicio1)
    (:objects
        z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 z13 z14 z15 z16 z17 z18 z19 z20 z21 z22 z23 z24 z25 - zona
        princesa1 - princesa
        principe1 - principe
        bruja1 - bruja
        profesor1 - profesor
        dicaprio1 - dicaprio
        oscar1 - oscar
        manzana1 - manzana
        rosa1 - rosa
        oro1 - oro
        alg - algoritmo
        luis - avatar
    )
    (:init
      (esta-en luis z1)
      (personaje-en princesa1 z4)
      (personaje-en principe1 z6)
      (personaje-en bruja1 z15)
      (personaje-en profesor1 z10)
      (personaje-en dicaprio1 z20)
      (objeto-en oscar1 z13)
      (objeto-en manzana1 z3)
      (objeto-en rosa1 z18)
      (objeto-en oro1 z23)
      (objeto-en alg z16)
      (orientado luis Sur)
      (or-sig-iz Norte Oeste)
      (or-sig-iz Oeste Sur)
      (or-sig-iz Sur Este)
      (or-sig-iz Este Norte)
      (or-sig-der Norte Este)
      (or-sig-der Este Sur)
      (or-sig-der Sur Oeste)
      (or-sig-der Oeste Norte)
    ;; z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 z13 z14 z15 z16 z17 z18 z19 z20 z21 z22 z23 z24 z25
        (conectadas z1 z2 Este)
        (conectadas z2 z1 Oeste)
        (conectadas z2 z3 Este)
        (conectadas z3 z2 Oeste)
        (conectadas z3 z4 Este)
        (conectadas z4 z3 Oeste)
        (conectadas z4 z5 Este)
        (conectadas z5 z4 Oeste)
        (conectadas z5 z6 Este)
        (conectadas z6 z5 Oeste)
        (conectadas z6 z7 Este)
        (conectadas z7 z6 Oeste)
        (conectadas z7 z8 Este)
        (conectadas z8 z7 Oeste)
        (conectadas z8 z9 Este)
        (conectadas z9 z8 Oeste)
        (conectadas z9 z10 Este)
        (conectadas z10 z9 Oeste)
        (conectadas z10 z11 Este)
        (conectadas z11 z10 Oeste)
        (conectadas z11 z12 Este)
        (conectadas z12 z11 Oeste)
        (conectadas z12 z13 Este)
        (conectadas z13 z12 Oeste)
        (conectadas z13 z14 Este)
        (conectadas z14 z13 Oeste)
        (conectadas z14 z15 Este)
        (conectadas z15 z14 Oeste)
        (conectadas z15 z16 Este)
        (conectadas z16 z15 Oeste)
        (conectadas z16 z17 Este)
        (conectadas z17 z16 Oeste)
        (conectadas z17 z18 Este)
        (conectadas z18 z17 Oeste)
        (conectadas z18 z19 Este)
        (conectadas z19 z18 Oeste)
        (conectadas z19 z20 Este)
        (conectadas z20 z19 Oeste)
        (conectadas z20 z21 Este)
        (conectadas z21 z20 Oeste)
        (conectadas z21 z22 Este)
        (conectadas z22 z21 Oeste)
        (conectadas z22 z23 Este)
        (conectadas z23 z22 Oeste)
        (conectadas z23 z24 Este)
        (conectadas z24 z23 Oeste)
        (conectadas z24 z25 Este)
        (conectadas z25 z24 Oeste)
    )
    (:goal (and
                (tiene-objeto princesa1)
                (tiene-objeto principe1)
                (tiene-objeto bruja1)
                (tiene-objeto dicaprio1)
                (tiene-objeto profesor1)
            )
    )
)
