(define (problem prueba1-ej5)
    (:domain ejercicio5)
    (:objects
        z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 z13 z14 z15 z16 z17 z18 z19 z20 z21 z22 z23 z24 z25 - zona
        princesa1 - Princesa
        principe1 - Principe
        bruja1 - Bruja
        profesor1 - Profesor
        leonardo1 - Leonardo
        oscar1 - oscar
        manzana1 - manzana
        rosa1 - rosa
        oro1 - oro
        alg - algoritmo
        zap - Zapatilla
        luis - Player
        oscar2 - oscar
        manzana2 - manzana
        rosa2 - rosa
        oro2 - oro
        alg2 - algoritmo
        zap2 - Zapatilla
    )
    (:init
      (en luis z1)
      (en princesa1 z4)
      ;(en zap z3)
      (en principe1 z6)
      (en bruja1 z15)
      (en profesor1 z10)
      (en leonardo1 z20)
      (en oscar1 z13)
      (en manzana1 z3)
      (en rosa1 z18)
      (en oro1 z23)
      (en alg z16)
      (en oscar2 z13)
      (en manzana2 z3)
      (en rosa2 z18)
      (en oro2 z23)
      (en alg2 z16)
      (mochila-vacia luis)
      (mano-vacia luis)
      (= (huecos-bolsillo bruja1) 3)
      (= (huecos-bolsillo profesor1) 3)
      (= (huecos-bolsillo leonardo1) 3)
      (= (huecos-bolsillo principe1) 3)
      (= (huecos-bolsillo princesa1) 3)
      ;(es-bosque z10)
      (orientado luis sur)
      (or-sig-iz norte oeste)
      (or-sig-iz oeste sur)
      (or-sig-iz sur este)
      (or-sig-iz este norte)
      (or-sig-der norte este)
      (or-sig-der este sur)
      (or-sig-der sur oeste)
      (or-sig-der oeste norte)
    ;; z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 z13 z14 z15 z16 z17 z18 z19 z20 z21 z22 z23 z24 z25
        (conectadas z1 z2 este)
        (conectadas z2 z1 oeste)
        (conectadas z2 z3 este)
        (conectadas z3 z2 oeste)
        (conectadas z3 z4 este)
        (conectadas z4 z3 oeste)
        (conectadas z4 z5 este)
        (conectadas z5 z4 oeste)
        (conectadas z5 z6 este)
        (conectadas z6 z5 oeste)
        (conectadas z6 z7 este)
        (conectadas z7 z6 oeste)
        (conectadas z7 z8 este)
        (conectadas z8 z7 oeste)
        (conectadas z8 z9 este)
        (conectadas z9 z8 oeste)
        (conectadas z9 z10 este)
        (conectadas z10 z9 oeste)
        (conectadas z10 z11 este)
        (conectadas z11 z10 oeste)
        (conectadas z11 z12 este)
        (conectadas z12 z11 oeste)
        (conectadas z12 z13 este)
        (conectadas z13 z12 oeste)
        (conectadas z13 z14 este)
        (conectadas z14 z13 oeste)
        (conectadas z14 z15 este)
        (conectadas z15 z14 oeste)
        (conectadas z15 z16 este)
        (conectadas z16 z15 oeste)
        (conectadas z16 z17 este)
        (conectadas z17 z16 oeste)
        (conectadas z17 z18 este)
        (conectadas z18 z17 oeste)
        (conectadas z18 z19 este)
        (conectadas z19 z18 oeste)
        (conectadas z19 z20 este)
        (conectadas z20 z19 oeste)
        (conectadas z20 z21 este)
        (conectadas z21 z20 oeste)
        (conectadas z21 z22 este)
        (conectadas z22 z21 oeste)
        (conectadas z22 z23 este)
        (conectadas z23 z22 oeste)
        (conectadas z23 z24 este)
        (conectadas z24 z23 oeste)
        (conectadas z24 z25 este)
        (conectadas z25 z24 oeste)
        ; puntos de luis
        (= (puntos-jugador) 0)
        ; puntos para leonardo1
        (= (puntos leonardo1 oscar1) 10)
        (= (puntos leonardo1 rosa1) 1)
        (= (puntos leonardo1 manzana1) 3)
        (= (puntos leonardo1 alg) 4)
        (= (puntos leonardo1 oro1) 5)
        ; puntos para princesa1
        (= (puntos princesa1 oscar1) 5)
        (= (puntos princesa1 rosa1) 10)
        (= (puntos princesa1 manzana1) 1)
        (= (puntos princesa1 alg) 3)
        (= (puntos princesa1 oro1) 4)
        ; puntos para bruja1
        (= (puntos bruja1 oscar1) 4)
        (= (puntos bruja1 rosa1) 5)
        (= (puntos bruja1 manzana1) 10)
        (= (puntos bruja1 alg) 1)
        (= (puntos bruja1 oro1) 3)
        ; puntos para profesor1
        (= (puntos profesor1 oscar1) 3)
        (= (puntos profesor1 rosa1) 4)
        (= (puntos profesor1 manzana1) 5)
        (= (puntos profesor1 alg) 10)
        (= (puntos profesor1 oro1) 1)
        ; puntos para principe1
        (= (puntos principe1 oscar1) 1)
        (= (puntos principe1 rosa1) 3)
        (= (puntos principe1 manzana1) 4)
        (= (puntos principe1 alg) 5)
        (= (puntos principe1 oro1) 10)


        (= (puntos leonardo1 oscar2) 10)
        (= (puntos leonardo1 rosa2) 1)
        (= (puntos leonardo1 manzana2) 3)
        (= (puntos leonardo1 alg2) 4)
        (= (puntos leonardo1 oro2) 5)
        ; puntos para princesa1
        (= (puntos princesa1 oscar2) 5)
        (= (puntos princesa1 rosa2) 10)
        (= (puntos princesa1 manzana2) 1)
        (= (puntos princesa1 alg2) 3)
        (= (puntos princesa1 oro2) 4)
        ; puntos para bruja1
        (= (puntos bruja1 oscar2) 4)
        (= (puntos bruja1 rosa2) 5)
        (= (puntos bruja1 manzana2) 10)
        (= (puntos bruja1 alg2) 1)
        (= (puntos bruja1 oro2) 3)
        ; puntos para profesor1
        (= (puntos profesor1 oscar2) 3)
        (= (puntos profesor1 rosa2) 4)
        (= (puntos profesor1 manzana2) 5)
        (= (puntos profesor1 alg2) 10)
        (= (puntos profesor1 oro2) 1)
        ; puntos para principe1
        (= (puntos principe1 oscar2) 1)
        (= (puntos principe1 rosa2) 3)
        (= (puntos principe1 manzana2) 4)
        (= (puntos principe1 alg2) 5)
        (= (puntos principe1 oro2) 10)
        ;distancias
        (= (distancia-total) 0)
        (= (distancia z1 z2) 2)
        (= (distancia z2 z1) 2)
        (= (distancia z2 z3) 2)
        (= (distancia z3 z2) 2)
        (= (distancia z3 z4) 2)
        (= (distancia z4 z5) 2)
        (= (distancia z4 z3) 2)
        (= (distancia z5 z4) 2)
        (= (distancia z5 z6) 2)
        (= (distancia z6 z5) 2)
        (= (distancia z6 z7) 2)
        (= (distancia z7 z6) 2)
        (= (distancia z7 z8) 2)
        (= (distancia z8 z7) 2)
        (= (distancia z9 z8) 2)
        (= (distancia z8 z9) 2)
        (= (distancia z9 z10) 2)
        (= (distancia z10 z9) 2)
        (= (distancia z10 z11) 2)
        (= (distancia z11 z10) 2)
        (= (distancia z11 z12) 2)
        (= (distancia z12 z11) 2)
        (= (distancia z12 z13) 2)
        (= (distancia z13 z12) 2)
        (= (distancia z13 z14) 2)
        (= (distancia z14 z15) 2)
        (= (distancia z14 z13) 2)
        (= (distancia z15 z14) 2)
        (= (distancia z15 z16) 2)
        (= (distancia z16 z15) 2)
        (= (distancia z16 z17) 2)
        (= (distancia z17 z16) 2)
        (= (distancia z17 z18) 2)
        (= (distancia z18 z17) 2)
        (= (distancia z18 z19) 2)
        (= (distancia z19 z18) 2)
        (= (distancia z19 z20) 2)
        (= (distancia z20 z19) 2)
        (= (distancia z20 z21) 2)
        (= (distancia z21 z20) 2)
        (= (distancia z21 z22) 2)
        (= (distancia z22 z21) 2)
        (= (distancia z22 z23) 2)
        (= (distancia z23 z22) 2)
        (= (distancia z23 z24) 2)
        (= (distancia z24 z23) 2)
        (= (distancia z24 z25) 2)
        (= (distancia z25 z24) 2)
    )
    (:goal (and
                (tiene-objeto princesa1)
                (tiene-objeto principe1)
                (tiene-objeto bruja1)
                (tiene-objeto leonardo1)
                (tiene-objeto profesor1)
                (<= (distancia-total) 700)
                (>= (puntos-jugador) 50)
            )
    )
)
